authapp/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name = 'authapp'
urlpatterns = [
    path('#', views.login,name="login"),
    path('register/',views.register,name="register"),
    path('logout/',views.logout,name='logout'),
    path('index/',views.view_user_data,name="index"),
    path('addmovie/',views.add_movie,name="add_movie"),
    path("filterdmovie/",views.filter_movies,name="filter_movies"),
    path('searchmovie/',views.movie_searcher,name='movie_searcher'),
    path('movies/<int:id>/',views.view_movie_info,name="view_movie_info"),
    path('all_movies/',views.all_movies,name="all_movies"),
    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path("searchmovies/",views.search_movies,name="search_movies"),




]

homeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "homeapp"
urlpatterns = [

    path('home/', views.home, name="home"),
    path('index/',views.index,name="index"),

]

movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("authapp.urls")),
    path('home/',include('homeapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserData(models.Model):
    username = models.CharField(max_length=250)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    email = models.EmailField(max_length=250, default='SOME STRING')
    password1 = models.CharField(max_length=250, default='SOME STRING')
    password2 = models.CharField(max_length=250, default='SOME STRING')

    dp = models.ImageField(upload_to="gallery", blank=True, null=True)

    def __str__(self):
        return self.username


class AddMovie(models.Model):
    title = models.CharField(max_length=250, default="SOME STRING")
    release = models.DateTimeField()
    description = models.TextField()
    movie_length = models.IntegerField()
    cover = models.ImageField(upload_to="gallery")
    genre = models.CharField(max_length=250, default="SOME STRING")
    url = models.CharField(max_length=250, default="SOME STRING")
    actor = models.CharField(max_length=250, blank=True, null=True)
    rating = models.CharField(max_length=250, default='SOME STRING')
    comment = models.CharField(max_length=250, default="SOME STRING")

    # def average_rating(self):
    #     ratings = self.ratings.all()
    #     if ratings:
    #         return sum([rating.rating for rating in ratings]) / len(ratings)
    #     return 0
    #
    #
    #
    def __str__(self):
        return self.title


class Comment(models.Model):
    movie = models.ForeignKey(AddMovie, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.TextField()

    def __str__(self):
        return f'Comment by {self.user.username} on {self.movie.title}'


# class Rating(models.Model):
#     movie = models.ForeignKey('AddMovie', on_delete=models.CASCADE, related_name='ratings')
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     rating = models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     class Meta:
#         unique_together = ('movie', 'user')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block title %}
    <title>Title</title>
    {% endblock %}
</head>
<body>

<! Search Bar -->
<form class="max-w-full mx-fit" method="POST" action="{% url 'authapp:search_movies' %}">
    {% csrf_token %}
    <div class="flex">
        <div class="relative w-full">
            <input type="text" name="search_query" id="search_query" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-none border-s-gray-50 border-s-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-s-gray-700  dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500" placeholder="Search Movies" required />
            <button type="submit" class="absolute top-0 end-0 p-2.5 text-sm font-medium h-full text-white bg-blue-700 rounded-none border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
                <span class="sr-only">Search</span>
            </button>
        </div>
    </div>
</form>
<! navbar -->

<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
  <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">

      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Movie</span>
  </a>
  <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

      <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>


        <img class="w-8 h-8 rounded-full" src="{{user.profile.profile_image.url}}" alt="user photo" style="width:45px;height:45px;">





          {% if user_data.dp %}
          <div class="username">
       <h4>Welcome {{user_data.username}}</h4>
          </div>
            {% endif %}

      <!-- Dropdown menu -->
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">

            {% if user.username %}
        <div class="px-4 py-3">

          <span class="block text-sm text-gray-900 dark:text-white">{{user.username}}</span>
          <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">{{user.email}}</span>

        </div>
           {% endif %}

        <ul class="py-2" aria-labelledby="user-menu-button">

          <li>
            <a href="{% url 'authapp:user_profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
          </li>

          <li>
            <a href="{% url 'authapp:logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
          </li>
        </ul>
      </div>
      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
  </div>

  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="{% url 'authapp:index' %}" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Home</a>
      </li>
      <li>
        <a href="{% url 'authapp:add_movie' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Add Movie</a>
      </li>
      <li>
        <a href="{% url 'authapp:filter_movies' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Filter Movies</a>
      </li>
      <li>
        <a href="{% url 'authapp:all_movies' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">All Movies</a>
      </li>

    </ul>
  </div>
  </div>
</nav>















{% block body %}
{% endblock %}
<script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>

</body>
</html>

templates/edit_comment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Edit Comment </title>
{% endblock %}
{% block body %}
<h1 class="max-w-sm mx-auto" >Edit Comment</h1>

<form method="POST"  action="{% url 'authapp:edit_comment' comment.id %}" class="max-w-sm mx-auto" >
    {% csrf_token %}
    <div class="mb-5">
        <label for="comment">Comment:</label><br>
        <textarea id="comment" name="comment" rows="4" cols="50">{{ comment.text }}</textarea>
    </div>
    <div class="mb-5">
        <label for="rating">Rating:</label><br>
        <input type="number" id="rating" name="rating" min="1" max="5" value="{{ comment.rating }}">
    </div>
    <input type="hidden" name="movie_id" value="{{ comment.movie_id }}">

    <button type="submit" class="bg-green-500 hover:bg-green-400 text-white font-bold py-2 px-4 border-b-4 border-green-700 hover:border-green-500 rounded"> Submit </button>

</form>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Home </title>
{% endblock %}
{% block body %}
<a href="{% url 'authapp:logout' %}">Logout</a> <br>
<a href="{% url 'authapp:login' %}">Login</a>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<title>Index</title>
{% endblock %}
{% block body %}

<div class="background">

<div class="backdrop-blur-md overflow-x-auto  h-screen  bg-gradient-to-b ">








<div id="alert-additional-content-3" class="container mx-auto p-4 mb-4 text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800" role="alert">

  <div class="flex items-center">

    <svg class="flex-shrink-0 w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>

    <h3 class="text-center font-medium">Welcome {{user.username}}</h3>

  </div>
  <div class="mt-2 mb-4 ">
  Your are logged in successfully
  </div>
  <div class="flex">
    <button type="button" class="text-white bg-green-800 hover:bg-green-900 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-xs px-3 py-1.5 me-2 text-center inline-flex items-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
      <svg class="me-2 h-3 w-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 14">
        <path d="M10 0C4.612 0 0 5.336 0 7c0 1.742 3.546 7 10 7 6.454 0 10-5.258 10-7 0-1.664-4.612-7-10-7Zm0 10a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z"/>
      </svg><a href="{% url 'authapp:user_profile' %}">View Profile</a>

    </button>
    <button type="button" class="text-green-800 bg-transparent border border-green-800 hover:bg-green-900 hover:text-white focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-xs px-3 py-1.5 text-center dark:hover:bg-green-600 dark:border-green-600 dark:text-green-400 dark:hover:text-white dark:focus:ring-green-800" data-dismiss-target="#alert-additional-content-3" aria-label="Close">
      Dismiss
    </button>
  </div>

</div>

   <div class="backdrop-blur-md overflow-x-auto bg-gradient-to-b">
        <div class="flex flex-wrap justify-center">
            {% for movies in all_movies %}
            <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 mx-2 my-2">
                <a href="#">
                    <img class="p-8 rounded-t-lg" src="{{movies.cover.url}}" alt="product image" style="width:300px;height:400px;"/>
                </a>
                <div class="px-5 pb-5">
                    <a href="#">
                        <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{movies.title}}</h5>
                    </a>
                    <div class="flex items-center mt-2.5 mb-5">
                        <div class="flex items-center space-x-1 rtl:space-x-reverse">
                            <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                            </svg>
                            <!-- Add more rating stars here -->
                        </div>
                        <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">{{movies.rating}}</span>
                    </div>
                    <div class="flex items-center justify-between">

                        {% if movies.id %}
                        <a href="{% url 'authapp:view_movie_info' movies.id %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">View</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>







  </div>
</div>




{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block title %}
    <title>Title</title>
    {% endblock %}
</head>
<body>




<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <form action="" method="POST">
        {% csrf_token %}
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">

    <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign in to your account</h2>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" action="" method="POST">
      <div>
        <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
        <div class="mt-2">
          <input id="username" name="username" type="text"  required class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>

      <div>
        <div class="flex items-center justify-between">
          <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
          <div class="text-sm">

          </div>
        </div>
        <div class="mt-2">
          <input id="password" name="password1" type="password" autocomplete="current-password" required class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>

      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Sign in</button>
      </div> <br>
        <div>
      <a href="{% url 'homeapp:home' %}" class ="flex w-full justify-center rounded-md bg-green-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600"">Go Home</a>
          </div>
    </form>

    <p class="mt-10 text-center text-sm text-gray-500">
      Not a member?
      <a href="{% url 'authapp:register' %}" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">Click here to register</a>
    </p>
  </div>
    </form>
                {% if messages %}
 <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md" role="alert">
  <div class="flex">
    <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
    <div>
         {% for message in messages %}
      <p class="font-bold">Alert</p>
      <p class="text-sm">{{message}}</p>
         {% endfor %}
                {% endif %}
    </div>
  </div>
</div>
</div>


</body>

</html>

templates/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>User Profile </title>
{% endblock %}
{% block body %}


<div class="bg-gray-100">
    <div class="container mx-auto py-8">
        <div class="grid grid-cols-4 sm:grid-cols-12 gap-6 px-4">
            <div class="col-span-4 sm:col-span-3">
                <div class="bg-white shadow rounded-lg p-6">
                    <div class="flex flex-col items-center">
                        <img src="{{user.profile.profile_image.url}}" class="w-32 h-32 bg-gray-300 rounded-full mb-4 shrink-0">

                        </img>
                        <h1 class="text-xl font-bold">{{user.username}}</h1>

                        <div class="mt-6 flex flex-wrap justify-center">

                        </div>
                    </div>

                    <div class="flex flex-col">


                    </div>
                </div>
            </div>
            <div class="col-span-4 sm:col-span-9">
                <div class="bg-white shadow rounded-lg p-6">
                    <h2 class="text-xl font-bold mb-4">Current Details</h2>

<p>Username:{{request.user.username}}</p>
<p>Email:{{request.user.email}}</p>

<p>First Name: {{ request.user.first_name }}</p>
<p>Last Name: {{ request.user.last_name }}</p>


                    <div class="flex justify-center items-center gap-6 my-6">





                    </div>



                    <div class="mb-6">


                    </div>
                    <div class="mb-6">

                    </div>
                    <div class="mb-6">


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<! comments -->

<div class="bg-gray-100">
    <div class="container mx-auto py-8">
        <div class="grid grid-cols-4 sm:grid-cols-12 gap-6 px-4">
            <div class="col-span-4 sm:col-span-3">

            </div>











            <div class="col-span-4 sm:col-span-12">
                <div class="bg-white shadow rounded-lg p-6">
                    <h2 class="text-xl font-bold mb-6">My Comments</h2>
                    {% for comment in comments %}

                        <li>

                            <div class="flex items-center bg-blue-500 text-white text-md font-bold px-4 py-3" role="alert">
                                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                                    <p><b>"{{ comment.text }}" </b>  in {{comment.movie}} on {{comment.created_at|date:"Y-m-d H:i:s"}}</p>
                                <button class="bg-green-500 hover:bg-green-400 text-white font-bold py-2 px-4 border-b-4 border-green-700 hover:border-green-500 rounded">    <a href="{% url 'authapp:edit_comment' comment.id %}">Edit</a> </button>
                            </div>


                        </li>
                        {% endfor %}





                    <div class="flex justify-center items-center gap-6 my-6">








                    </div>
                </div>
            </div>
        </div>
    </div>
</div>







<! edit user data -->
<div class="bg-gray-100">
    <div class="container mx-auto py-8">
        <div class="grid grid-cols-4 sm:grid-cols-12 gap-6 px-4">
            <div class="col-span-4 sm:col-span-3">

            </div>











            <div class="col-span-4 sm:col-span-12">
                <div class="bg-white shadow rounded-lg p-6">
                    <h2 class="text-xl font-bold mb-6">Edit User Data</h2>

                            <form method="POST" enctype="multipart/form-data" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_username" class="block text-sm font-medium text-gray-700">Username</label>
        {{ user_form.username }}
    </div>
    <div class="mb-4">
        <label for="id_first_name" class="block text-sm font-medium text-gray-700">First Name</label>
        {{ user_form.first_name }}
    </div>
    <div class="mb-4">
        <label for="id_last_name" class="block text-sm font-medium text-gray-700">Last Name</label>
        {{ user_form.last_name }}
    </div>
    <div class="mb-4">
        <label for="id_email" class="block text-sm font-medium text-gray-700">Email</label>
        {{ user_form.email }}
    </div>
    <div class="mb-4">
        <label for="id_profile_image" class="block text-sm font-medium text-gray-700"></label>
        {{ profile_form.profile_image }}
    </div>
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update</button>
</form>





                <div class="flex justify-center items-center gap-6 my-6">








                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
















{% endblock %}